dev:
  domain: "mzf.one"
  postgres_dsn: "" # postgres://user:password@host:port/database?option=value

prod:
  domain: "mzf.one"
  postgres_dsn: "" # postgres://user:password@host:port/database?option=value
