dev:
  show_error_details: true
  debug: true
  callback_url: "http://localhost:8000/auth/callback"
  postgres_dsn: ""

  discord:
    client_id: ""
    client_secret: ""

  github:
    client_id: ""
    client_secret: ""
    
prod:
  show_error_details: true
  debug: true

  callback_url: "http://localhost:8000/auth/callback"
  postgres_dsn: ""

  discord:
    client_id: ""
    client_secret: ""

  github:
    client_id: ""
    client_secret: ""