dev:
  show_error_details: false
  debug: true
  secrets:
    - ""
    - ""
    - ""
  signing_key: ""
  callback_url: "http://localhost:8000/api/auth/callback"

  discord:
    client_id: ""
    client_secret: ""